### ISSUE TITLE
omnivore/csv2json leser ikke NVDB-format

### ISSUE THREAD

**Issue by ellvtr** [GeoForum/geoforumtutorials#1]
Hei @alexanno, omnivore/csv2json leser punkt-geometri som to kolonner med lat-lon, men nvdb-formatet har geometri som wkt-string i en kolonne.
https://github.com/mapbox/leaflet-omnivore
https://github.com/mapbox/csv2geojson#api
https://github.com/GeoForum/geoforumtutorials/tree/master/www/veiledning01/data

See issue på trello her:
https://trello.com/c/Qc8lpjeJ/6-omnivore-csv2json-leser-ikke-nvdb-format

**Comment by alexanno** [comment]
Omnivore parser jo WKT rimelig greit - spesielt POINT. Jf: https://www.mapbox.com/mapbox.js/example/v1.0.0/omnivore-wkt/

CSV kan jo nesten like enkelt parses ved helt standard Javascript med split() 
fks: 
lines = textstring.split(/\r\n|\r|\n/g);//split on \r\n or \n or \r
//split each line
"61450.00,7297350.00,640.965, POINT(123 321)".split(",");

Hvis det viser seg å være problematisk pga komma inne i elementene eller lignende, så finnes jo dedikerte csv->json-parsere som fks: http://papaparse.com/ 

og så bruke WKT på elementene som krever det.

**Comment by ellvtr** [comment]
Fant selv frem til papaparse og har implementert den - den håndterer store datamengder veldig bra! Har beskrevet dette i seneste push:
https://github.com/GeoForum/geoforumtutorials/commit/1f811b7f65f176d81b50faeb1e5e2a96ba0e3d30

Har pt issues med convertering fra 'EPSG:32633' til "EPSG:3857", verdiene er helt feil, de skrives ut i browserens console.log hvis noen er interessert.

**Comment by alexanno** [comment]
Leaflet bruker 3857 for visning. Det er mercator. Men i "Javascripten" brukes WGS84. Altså bruker man fks: L.marker([63.321312, 10.123132]) som blir "interntransformert" til 3857 for visning.

**Comment by ellvtr** [comment]
Regnet egentlig med at espg-kodene var unike, men ser nå at epsg:3857 defineres på to foskjellig måter:
http://spatialreference.org/ref/?search=epsg%3A3857
hhv:
+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
og: 
+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs
